import { Nav } from "@/components/nav/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-2 relative  flex h-screen">
          <Nav />
          <div className="relative w-full h-full mx-2 rounded-lg overflow-hidden overflow-y-auto">
            <Header />
            <main className="relative h-[86vh]  overflow-hidden overflow-y-auto rounded-lg bg-[rgba(255,255,255,0.1)]">
              <div className="relative h-full w-full overflow-hidden overflow-y-auto rounded-lg">{children}</div>
            </main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
